# Generated by Django 5.2.13 on 2026-04-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(max_length=50, unique=True)),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('tempat_lahir', models.CharField(blank=True, max_length=100)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('alamat', models.TextField(blank=True)),
                ('nama_ayah', models.CharField(blank=True, max_length=150)),
                ('nama_ibu', models.CharField(blank=True, max_length=150)),
                ('nama_wali', models.CharField(blank=True, max_length=150)),
                ('no_wa_wali', models.CharField(blank=True, max_length=20)),
                ('kelas', models.CharField(blank=True, max_length=100)),
                ('kamar', models.CharField(blank=True, max_length=100)),
                ('tanggal_masuk', models.DateField(blank=True, null=True)),
                ('tahun_ajaran', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif'), ('alumni', 'Alumni')], default='aktif', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nama_lengkap'],
            },
        ),
    ]
