# Generated by Django 5.2.13 on 2026-04-24 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('saldo_awal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('kategori', models.CharField(max_length=100)),
                ('nominal_default', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tipe', models.CharField(choices=[('bulanan', 'Bulanan'), ('tahunan', 'Tahunan'), ('sekali_bayar', 'Sekali Bayar')], max_length=20)),
                ('wajib', models.BooleanField(default=True)),
                ('aktif', models.BooleanField(default=True)),
                ('denda_per_hari', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deskripsi', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_bulan', models.PositiveSmallIntegerField(default=1)),
                ('periode_tahun', models.PositiveSmallIntegerField(default=2026)),
                ('nominal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('diskon', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('denda', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tagihan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_dibayar', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sisa_tagihan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('jatuh_tempo', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('belum_bayar', 'Belum Bayar'), ('sebagian', 'Sebagian'), ('lunas', 'Lunas'), ('terlambat', 'Terlambat')], default='belum_bayar', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='students.student')),
                ('jenis_pembayaran', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.paymenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=100)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('bukti', models.FileField(blank=True, null=True, upload_to='expense/')),
                ('catatan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.cashaccount')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=100)),
                ('sumber', models.CharField(max_length=150)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('bukti', models.FileField(blank=True, null=True, upload_to='income/')),
                ('catatan', models.TextField(blank=True)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.cashaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_bayar', models.DateField(auto_now_add=True)),
                ('jumlah_bayar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metode_bayar', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer'), ('qris', 'QRIS')], max_length=20)),
                ('bukti_transfer', models.ImageField(blank=True, null=True, upload_to='payments/')),
                ('nomor_transaksi', models.CharField(editable=False, max_length=50, unique=True)),
                ('catatan', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.bill')),
                ('diterima_oleh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
