# Generated by Django 5.2.13 on 2026-04-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PondokProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pondok', models.CharField(blank=True, max_length=150)),
                ('alamat', models.CharField(blank=True, max_length=255)),
                ('kota', models.CharField(blank=True, max_length=100)),
                ('telepon', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('kepala_pesantren', models.CharField(blank=True, max_length=150)),
                ('website', models.URLField(blank=True)),
                ('motto', models.CharField(blank=True, max_length=255)),
                ('catatan', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil Pondok',
                'verbose_name_plural': 'Profil Pondok',
            },
        ),
    ]
