# Generated by Django 5.2.13 on 2026-04-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pondokprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pondokprofile',
            name='bank_atas_nama',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pondokprofile',
            name='bank_nama',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pondokprofile',
            name='bank_nomor_rekening',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pondokprofile',
            name='bendahara_nama',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pondokprofile',
            name='bendahara_telepon',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='pondokprofile',
            name='qris_url',
            field=models.URLField(blank=True),
        ),
    ]
