from django.urls import path
from .views import (
    BillListView,
    BillStudentDetailView,
    BillInvoicePdfView,
    BillGenerateView,
    CashAccountCreateView,
    CashAccountDeleteView,
    CashAccountListView,
    CashAccountUpdateView,
    ExpenseCreateView,
    ExpenseDeleteView,
    ExpenseListView,
    ExpenseUpdateView,
    IncomeCreateView,
    IncomeDeleteView,
    IncomeListView,
    IncomeUpdateView,
    PaymentCreateView,
    PaymentListView,
    PaymentTypeCreateView,
    PaymentTypeDeleteView,
    PaymentTypeListView,
    PaymentTypeUpdateView,
    FinanceWorkflowView,
    WhatsAppReminderScheduleView,
)

app_name = "finance"

urlpatterns = [
    path("payment-types/", PaymentTypeListView.as_view(), name="payment_type_list"),
    path("payment-types/tambah/", PaymentTypeCreateView.as_view(), name="payment_type_create"),
    path("payment-types/<int:pk>/edit/", PaymentTypeUpdateView.as_view(), name="payment_type_update"),
    path("payment-types/<int:pk>/hapus/", PaymentTypeDeleteView.as_view(), name="payment_type_delete"),
    path("bills/", BillListView.as_view(), name="bill_list"),
    path("flow/", FinanceWorkflowView.as_view(), name="workflow"),
    path("bills/<int:pk>/", BillStudentDetailView.as_view(), name="bill_student_detail"),
    path("bills/<int:pk>/invoice.pdf", BillInvoicePdfView.as_view(), name="bill_invoice_pdf"),
    path("bills/generate/", BillGenerateView.as_view(), name="bill_generate"),
    path("bills/reminder-schedule/", WhatsAppReminderScheduleView.as_view(), name="reminder_schedule"),
    path("payments/", PaymentListView.as_view(), name="payment_list"),
    path("payments/tambah/<int:bill_id>/", PaymentCreateView.as_view(), name="payment_create"),
    path("cash-accounts/", CashAccountListView.as_view(), name="cash_account_list"),
    path("cash-accounts/tambah/", CashAccountCreateView.as_view(), name="cash_account_create"),
    path("cash-accounts/<int:pk>/edit/", CashAccountUpdateView.as_view(), name="cash_account_update"),
    path("cash-accounts/<int:pk>/hapus/", CashAccountDeleteView.as_view(), name="cash_account_delete"),
    path("income/", IncomeListView.as_view(), name="income_list"),
    path("income/tambah/", IncomeCreateView.as_view(), name="income_create"),
    path("income/<int:pk>/edit/", IncomeUpdateView.as_view(), name="income_update"),
    path("income/<int:pk>/hapus/", IncomeDeleteView.as_view(), name="income_delete"),
    path("expense/", ExpenseListView.as_view(), name="expense_list"),
    path("expense/tambah/", ExpenseCreateView.as_view(), name="expense_create"),
    path("expense/<int:pk>/edit/", ExpenseUpdateView.as_view(), name="expense_update"),
    path("expense/<int:pk>/hapus/", ExpenseDeleteView.as_view(), name="expense_delete"),
]
